In [2]:
import numpy as np

In [ ]:
#FONTOS!!!

# CSAK OTT LEHET HASZNÁLNI FOR LOOP-OT AHOL A FELADAT KÜLÖN KÉRI!

In [ ]:
#Készíts egy függvényt ami létre hoz egy nullákkal teli numpy array-t.
#Paraméterei: mérete (tupel-ként), default mérete pedig legyen egy (2,2)
#Be: (2,2)
#Ki: [[0,0],[0,0]]
#create_array()

In [4]:
def create_array(size = (2,2)):
    return np.zeros(size)

i = (2,4)
print(create_array(i))

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [ ]:
#Készíts egy függvényt ami a paraméterként kapott array-t főátlót feltölti egyesekkel
#Be: [[1,2],[3,4]]
#Ki: [[1,2],[3,1]]
#set_one()

In [ ]:
def set_one(matrix : np.array):
    np.fill_diagonal(matrix,1,)
    return matrix


In [ ]:
# Transzponáld a paraméterül kapott mártix-ot:
# Be: [[1, 2], [3, 4]]
# Ki: [[1, 2], [3, 4]]
# do_transpose()

In [6]:
def do_transpose(matrix : np.array):
    return np.transpose(matrix)

i = np.array([[1, 2], [3, 4]])
print(do_transpose(i))

[[1 3]
 [2 4]]


In [ ]:
# Készíts egy olyan függvényt ami az array-ben lévő értékeket N tizenedjegyik kerekíti, alapértelmezetten 
# Be: [0.1223, 0.1675], n = 2
# Ki: [0.12, 0.17]
# round_array()

In [ ]:
def round_array(array_inp: np.array, N = 2):
    return  np.round(array_inp,N)

In [ ]:
# Készíts egy olyan függvényt, ami a bementként  0 és 1 ből álló tömben a 0 - False-ra az 1 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# bool_array()

In [ ]:
def bool_array(input_arr: np.array):
    inverted = np.invert(input_arr[True,False])
    return inverted

In [ ]:
# Készíts egy olyan függvényt, ami a bementként  0 és 1 ből álló tömben a 1 - False-ra az 0 True-ra cserélni
# Be: [[1, 0, 0], [1, 1, 1],[0, 0, 0]]
# Ki: [[ True False False], [ True  True  True], [False False False]]
# invert_bool_array()

In [ ]:
def invert_bool_array(input_arr: np.array):
    inverted = np.invert(input_arr[True,False])
    return ~inverted

In [ ]:
# Készíts egy olyan függvényt ami a paraméterként kapott array-t kilapítja
# Be: [[1,2], [3,4]]
# Ki: [1,2,3,4]
# flatten()

In [ ]:
def flatten(input: np.array):
    return input.flatten()